name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK (Skip Gradle Validation)
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HalaVoice-App
          path: build/app/outputs/flutter-apk/app-release.apk
